server:
  port: 8080
  
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.assoft.user.entity
  config-location: classpath:mybatis/mybatis-config.xml
#showSql
logging:
  level:
    com:
      assoft:
        user:
          mapper : debug
          
    